### ISSUE TITLE
$.holdReady is not a function

### ISSUE THREAD

**Issue by alexzuza** [DevExpress/devextreme-angular#406]
devextreme-angular doesn't work with jquery ^3.2.0 because `$.holdReady` has been deprecated

http://stackoverflow.com/questions/42868638/strange-error-in-angular-cli-themes-js236-uncaught-typeerror-holdready-is-no

**Comment by artcab** [comment]
Yes, this is major issue, preventing development

**Comment by markblandford** [comment]
I'm having the same problem. I've had to temporarily add a separate dependency on jquery 3.1.1 to workaround this.

**Comment by GoshaFighten** [comment]
This issue was caused by the [$.holdReady is broken in 3.2.0](https://github.com/jquery/jquery/issues/3573) bug in jQuery 3.2.0. jQuery fixed in version 3.2.1 and we also changed our code in the context of the [DevExtreme fails with the "$.holdReady is not a function" error when jQuery 3.2.0 is used](https://www.devexpress.com/Support/Center/Question/Details/T494217).
